// THIS FILE IS GENERATED — DO NOT EDIT BY HAND.
// Regenerate by running:
//     BMM_REGEN_PROTOCOL_TS=1 cargo test --test protocol_typescript
// from src-tauri/, then commit the updated file.
//
// Source of truth: media_metadata::model in src-tauri/src/media_metadata/model/.


// This file has been generated by Specta. Do not edit this file manually.
export type AlphaMode = "none" | "present";

/**
 *  One attached file (Matroska Attachments, MP4 mdat-by-handler, ...).  The
 *  payload itself is **not** read at identification time.
 */
export type Attachment = {
	/**  1-based sequence number in the file (matches `mkvmerge -J` ordering). */
	id: number,
	fileName: string,
	mimeType: string | null,
	description: string | null,
	/**  Bytes of the payload.  We seek past, not read. */
	size: number,
	/**  Hex-encoded UID when the source format provides one (Matroska FileUID). */
	uidHex: string | null,
};

/**
 *  Decoded audio codec-private blob.  See [`super::track_properties_video::VideoCodecConfig`]
 *  for the rationale on the shared opt-in struct shape.
 */
export type AudioCodecConfig = {
	profileName: string | null,
	/**  MPEG-4 Audio Object Type (5 for AAC SBR, 29 for PS, ...). */
	aacObjectType: number | null,
	aacFrameLength: number | null,
	aacSbrPresent: boolean | null,
	aacPsPresent: boolean | null,
	flacMinBlockSize: number | null,
	flacMaxBlockSize: number | null,
	flacMinFrameSize: number | null,
	flacMaxFrameSize: number | null,
	flacTotalSamples: number | null,
	/**  MD5 of the unencoded audio data (FLAC STREAMINFO last 16 bytes). */
	flacMd5Hex: string | null,
	rawHex: string | null,
};

export type AudioEmphasis = "none" | "cdAudio" | "ccittJ17" | "fm5025" | "fm7550" | "phonoRiaa" | "phonoIecN78" | "phonoTeldec" | "phonoEmi" | "phonoColumbiaLp" | "phonoLondon" | "phonoNartb" | "other";

/**
 *  Audio-track-only properties.  Populated only on tracks whose `trackType` is
 *  `Audio`.
 */
export type AudioTrackProperties = {
	samplingFrequency: number | null,
	outputSamplingFrequency: number | null,
	channels: number | null,
	channelLayout: ChannelLayout | null,
	bitDepth: number | null,
	emphasis: AudioEmphasis | null,
	/**  Nominal per-frame duration in nanoseconds (Matroska `DefaultDuration`). */
	defaultDurationNs: number | null,
	codecConfig: AudioCodecConfig | null,
};

/**
 *  One block-addition mapping (`block_addition_mapping_t` in mkvtoolnix).  The
 *  `id_type` is the source FOURCC (e.g. `dvcC`); `data_hex` is the raw
 *  box payload, hex-encoded.  PARSER-179.
 * 
 *  PARSER-228: `id_name` (`BlockAddIDName`) and `id_value` (`BlockAddIDValue`)
 *  are carried alongside `id_type`/`data_hex`, mirroring the full
 *  `block_addition_mapping_t` mkvtoolnix keeps — mappings that rely on the
 *  value or a descriptive name no longer lose that information.
 */
export type BlockAdditionMapping = {
	idType: string,
	dataHex: string,
	/**  `BlockAddIDName`, when present. */
	idName: string | null,
	/**  `BlockAddIDValue`, when present. */
	idValue: number | null,
};

/**
 *  Best-effort channel layout description.  `channels` is the count; `kind`
 *  is the canonical layout name when known.
 */
export type ChannelLayout = {
	channels: number,
	kind: ChannelLayoutKind | null,
	/**
	 *  Raw bitmap when the source format provides one (Matroska
	 *  `ChannelPositions`, WAV channel mask, ...).  Hex-encoded little-endian.
	 */
	rawMaskHex: string | null,
};

export type ChannelLayoutKind = "mono" | "stereo" | "layout21" | "layout30" | "layout31" | "layout40" | "layout41" | "layout50" | "layout51" | "layout61" | "layout71" | "layout714" | "other";

/**
 *  Identification-time summary of the chapter editions in a file.  We do not
 *  extract individual chapter titles / timecodes at identification time.
 */
export type ChapterSummary = {
	/**  Total entries summed across all editions. */
	numEntries: number,
	/**  Number of distinct editions / playlists. */
	numEditions: number,
};

export type ChromaFormat = "monochrome" | "yuv420" | "yuv422" | "yuv444" | "other";

export type ChromaSiting = {
	horizontal: number,
	vertical: number,
};

export type ChromaSubsampling = {
	horizontal: number,
	vertical: number,
};

/**  CIE 1931 (x,y) chromaticity coordinate.  Range [0, 1]. */
export type Chromaticity = {
	x: number | null,
	y: number | null,
};

/**
 *  Typed codec descriptor.  The container's CodecID is exposed as `id` (raw
 *  string for Matroska, FOURCC for AVI/MP4, stream_type byte for MPEG-TS);
 *  `name` is the catalogue lookup; `codecPrivate` carries the codec-private
 *  blob (typed properties live on the per-track domain sub-tree).
 */
export type CodecInfo = {
	id: string,
	name: string | null,
	codecPrivate: CodecPrivate | null,
};

/**
 *  Codec-private blob.  We expose both the byte length and a hex dump so the
 *  frontend can show a length without having to copy the whole hex string.
 */
export type CodecPrivate = {
	length: number,
	hex: string,
};

/**
 *  Decoded `Colour` element (Matroska) / `colr` box (MP4) / colr-related H.273
 *  signalling — typed sub-fields, never flattened into the parent.
 */
export type ColorMetadata = {
	matrixCoefficients: number | null,
	transferCharacteristics: number | null,
	primaries: number | null,
	range: ColorRange | null,
	bitsPerChannel: number | null,
	chromaSubsampling: ChromaSubsampling | null,
	cbSubsampling: ChromaSubsampling | null,
	chromaSiting: ChromaSiting | null,
	maxCll: number | null,
	maxFall: number | null,
	master: MasterMetadata | null,
};

export type ColorRange = "unspecified" | "broadcast" | "full" | "matrixDerived";

/**
 *  Track-level properties shared across all track kinds.  Domain-specific
 *  fields live on `TrackProperties.video / audio / subtitle` — see
 *  [[feedback-protocol-shape]].
 */
export type CommonTrackProperties = {
	/**  Container-assigned 1-based number (Matroska TrackNumber, MP4 trackID). */
	number: number | null,
	/**
	 *  Stable unique id (Matroska TrackUID).  Hex-encoded because 64-bit
	 *  values can exceed JavaScript's safe-integer range.
	 */
	uidHex: string | null,
	/**  User-facing track name when the container provides one. */
	trackName: string | null,
	/**
	 *  Resolved language pair (ISO-639-2 + BCP-47 IETF).  See
	 *  [`crate::media_metadata::language::Language`].
	 */
	language: Language | null,
	enabled: TrackFlag,
	default: TrackFlag,
	forced: TrackFlag,
	hearingImpaired: boolean | null,
	visualImpaired: boolean | null,
	textDescriptions: boolean | null,
	original: boolean | null,
	commentary: boolean | null,
	seekPreRollNs: number | null,
	codecDelayNs: number | null,
	/**
	 *  Maximum payload size advertised by the container (Matroska
	 *  MaxBlockAdditionID descriptor, MP4 nalLengthSize, ...).  Optional.
	 */
	maxBlockAdditionId: number | null,
	/**
	 *  Container compression / encryption descriptors applied to the track
	 *  (Matroska ContentEncodings).  Human-readable algorithm names, e.g.
	 *  `["zlib"]`.  Empty when the track has none.
	 */
	contentEncodings: string[],
	/**  MPEG-TS / MPEG-PS stream identifier (PID on TS, stream_id on PS). */
	streamId: number | null,
	/**  Sub-stream identifier (BD audio sub-stream, PES private stream sub-id). */
	subStreamId: number | null,
	/**
	 *  MPEG-TS program number this track belongs to.  When set, matches one
	 *  of the [`super::container::ContainerProperties::programs`] entries.
	 */
	programNumber: number | null,
	/**
	 *  DVB teletext page number (`teletext_page` in mkvmerge JSON).  Only
	 *  populated for teletext substreams.
	 */
	teletextPage: number | null,
	/**
	 *  Other tracks sharing this packetized substream (MPEG-TS PES
	 *  multiplex with DVB-Sub subtitles, ...).  Holds Track.id values.
	 */
	multiplexedWith: number[],
	/**
	 *  Lowest cluster / segment-start timestamp seen during header walk.
	 *  Matroska-specific; `None` for all other containers.  Signed because
	 *  CodecDelay / negative cue offsets can push the first block's global
	 *  timestamp below zero (PARSER-138).
	 */
	minimumTimestampNs: number | null,
	/**  Number of Matroska Cue entries pointing at this track. */
	numIndexEntries: number | null,
};

/**
 *  Container-level metadata.  Mirrors `mkvmerge -J`'s container object as a
 *  floor but adds typed fields the v20 schema omits.
 */
export type Container = {
	/**  Did at least one reader's `probe()` claim this file? */
	recognized: boolean,
	/**  Is the recognised format fully supported (vs. probe-only)? */
	supported: boolean,
	/**  Typed format identifier — one variant per reader in the registry. */
	format: ContainerFormat,
	properties: ContainerProperties,
};

/**
 *  One variant per reader we ship.  Listed in roughly the same order the
 *  probe cascade tries them.  Add new variants here when adding a new
 *  format reader.
 */
export type ContainerFormat = "matroska" | "webM" | "mp4" | "quickTime" | "avi" | "ogg" | "webvtt" | "mpegTs" | "mpegPs" | "flv" | "realMedia" | "ivf" | "coreAudio" | "wav" | "flac" | "mp3" | "aac" | "ac3" | "eac3" | "dts" | "trueHd" | "tta" | "wavpack" | "avc" | "hevc" | "mpegVideo" | "vc1" | "dirac" | "dv" | "av1Obu" | "srt" | "ssaAss" | "vobSub" | "usf" | "microDvd" | "hdmvPgs" | "hdmvTextSt" | "vobButton" | "chapters" | "cdxa" | "hdSub" | "asf" | "unknown";

export type ContainerProperties = {
	title: string | null,
	muxingApp: string | null,
	writingApp: string | null,
	duration: DurationValue | null,
	segmentUidHex: string | null,
	previousSegmentUidHex: string | null,
	nextSegmentUidHex: string | null,
	dateUtc: string | null,
	/**
	 *  Source-file mux date in local time zone (ISO-8601).  Mirrors mkvmerge's
	 *  `date_local` field.
	 */
	dateLocal: string | null,
	isFragmented: boolean | null,
	/**  Matroska TimestampScale (ns per timestamp unit, default 1_000_000 = ms). */
	timestampScale: number | null,
	/**  MP4 movie timescale (units per second, default 600). */
	movieTimescale: number | null,
	majorBrand: string | null,
	compatibleBrands: string[],
	/**  Average bitrate when the container declares one (FLV, MP4 mdhd). */
	bitrateBps: number | null,
	programs: Program[],
	/**
	 *  Sibling files demuxed alongside the primary input (VobSub `.sub`,
	 *  multi-file AVI extents, ...).  File-system paths in the order they
	 *  were discovered.  Mirrors mkvmerge's `other_file` field.
	 */
	otherFiles: string[],
	/**  Blu-ray playlist metadata when the input is an `.mpls` playlist. */
	playlist: PlaylistInfo | null,
};

export type CropRect = {
	left: number,
	top: number,
	right: number,
	bottom: number,
};

export type Dimensions2D = {
	width: number,
	height: number,
};

export type DisplayUnit = "pixels" | "centimetres" | "inches" | "displayAspectRatio" | "unknown";

/**
 *  A duration carried as both nanoseconds and a pre-formatted string so the
 *  frontend never has to format integers itself.  The formatted form is
 *  `HH:MM:SS.fffffffff` (always nine fractional digits, no rounding).
 */
export type DurationValue = {
	ns: number,
	formatted: string,
};

export type FieldOrder = "progressive" | "tff" | "bff" | "undetermined";

export type HevcTier = "main" | "high";

export type InterlaceFlag = "progressive" | "interlaced" | "unknown";

/**  A track's resolved language pair. */
export type Language = {
	/**
	 *  Canonical ISO 639-2 alpha-3 code (terminologic when a B/T pair exists).
	 *  Renamed on the wire because serde's `camelCase` rule mangles fields
	 *  containing digits (`iso639_2` → `iso6392`); we keep the underscore.
	 */
	iso639_2: string,
	/**  BCP-47 IETF tag when the source provided one and it validated. */
	ietf: string | null,
	/**  English name lookup for display.  Always derived from `iso639_2`. */
	name: string | null,
};

/**  SMPTE ST 2086 mastering display metadata. */
export type MasterMetadata = {
	primaryR: Chromaticity | null,
	primaryG: Chromaticity | null,
	primaryB: Chromaticity | null,
	whitePoint: Chromaticity | null,
	/**  Maximum luminance in cd/m² (nits). */
	luminanceMax: number | null,
	luminanceMin: number | null,
};

/**
 *  Root struct returned by [`crate::media_metadata::parse`] on success.  The
 *  nested hierarchy is preserved across the wire — never flattened.  See
 *  [[feedback-protocol-shape]].
 */
export type MediaMetadata = {
	protocolVersion: number,
	fileName: string,
	fileSize: number,
	container: Container,
	tracks: Track[],
	attachments: Attachment[],
	chapters: ChapterSummary,
	tags: TagsBundle,
	warnings: Warning[],
};

/**
 *  Blu-ray / multi-file playlist metadata.  Mirrors mkvmerge's
 *  `playlist*` identification fields (sourced from
 *  `mm_mpls_multi_file_io.cpp`).  Populated only when the input is a
 *  `.mpls` playlist that demultiplexes to several `.m2ts` segment files.
 */
export type PlaylistInfo = {
	/**  Total duration across all segment files in the playlist. */
	duration: DurationValue | null,
	/**  Number of chapter entries declared by the playlist. */
	chapters: number,
	/**  Sum of segment-file sizes (bytes). */
	totalSize: number,
	/**  File-system paths of the segment files in playback order. */
	files: string[],
	/**
	 *  PARSER-182: the STN-table streams the playlist declares (video, then
	 *  audio, then PG), de-duplicated by PID across play items.  Mirrors the
	 *  stream objects mkvtoolnix retains on `stn_t`
	 *  (`mkvtoolnix/src/common/bluray/mpls.h:94-149`).
	 */
	streams: PlaylistStream[],
};

/**
 *  One STN-table stream of a Blu-ray playlist.  Mirrors mkvtoolnix's
 *  `stream_t` (`mkvtoolnix/src/common/bluray/mpls.h:94-101`), parsed in
 *  `mkvtoolnix/src/common/bluray/mpls.cpp:391-447`.  Surfaced so that the STN
 *  coding type, format/rate, character code, and sub-path/sub-clip linkage are
 *  no longer thrown away after parsing.
 */
export type PlaylistStream = {
	/**  Which STN group the stream belongs to (video / audio / PG). */
	kind: PlaylistStreamKind,
	/**  STN `stream_entry` stream_type (1 = play item, 2/3 = sub-path). */
	streamType: number,
	/**
	 *  BD stream coding type (0x02 MPEG-2, 0x1b AVC, 0x80 LPCM, 0x90 PGS,
	 *  0x92 TextST, ...).
	 */
	codingType: number,
	/**  Elementary stream PID inside the referenced clip. */
	pid: number,
	/**  Sub-path id (set only for stream_type 2/3). */
	subPathId: number,
	/**  Sub-clip id (set only for stream_type 2). */
	subClipId: number,
	/**  video_format / audio_format nibble as parsed. */
	format: number,
	/**  frame_rate / sample_rate nibble as parsed. */
	rate: number,
	/**  Text-subtitle character code (set only for TextST coding type). */
	characterCode: number,
	/**  ISO 639-2 alpha-3 language, when the coding type carries one. */
	language: string | null,
};

/**
 *  Which STN group an MPLS playlist stream came from.  Mirrors the three
 *  stream vectors retained on mkvtoolnix's `stn_t`
 *  (`mkvtoolnix/src/common/bluray/mpls.h:103-108`).
 */
export type PlaylistStreamKind = "video" | "audio" | "presentationGraphics";

/**
 *  One MPEG-TS / MPEG-PS program (a logical sub-mux).  Most files have
 *  exactly one program; multi-program TS files (broadcast captures) report
 *  every program here so the frontend can filter.
 */
export type Program = {
	programNumber: number,
	pmtPid: number | null,
	serviceName: string | null,
	serviceProvider: string | null,
	/**
	 *  Track IDs (matching [`super::track::Track::id`]) carried by this
	 *  program.
	 */
	trackIds: number[],
};

export type ProjectionMetadata = {
	kind: ProjectionType | null,
	pose: ProjectionPose | null,
	/**  Codec-private projection bytes, hex-encoded. */
	privateHex: string | null,
};

export type ProjectionPose = {
	yaw: number | null,
	pitch: number | null,
	roll: number | null,
};

export type ProjectionType = "rectangular" | "equirectangular" | "cubemap" | "mesh";

export type SampleAspectRatio = {
	num: number,
	den: number,
};

export type StereoMode = "mono" | "sideBySideLeftFirst" | "sideBySideRightFirst" | "topBottomLeftFirst" | "topBottomRightFirst" | "checkerboard" | "rowInterleaved" | "columnInterleaved" | "anaglyphCyanRed" | "anaglyphGreenMagenta" | "other";

/**
 *  Subtitle-track-only properties.  Populated only on tracks whose `trackType`
 *  is `Subtitles`.
 */
export type SubtitleTrackProperties = {
	/**
	 *  `true` for text-based codecs (SRT, ASS, WebVTT, USF, MicroDVD).
	 *  `false` for image / graphical codecs (PGS, VobSub, HDMV TextST).
	 */
	textSubtitles: boolean,
	/**
	 *  Detected source-file encoding for text subtitles (UTF-8, Windows-1252,
	 *  ...).  Always `None` for graphical formats.
	 */
	encoding: string | null,
	/**
	 *  Container-specific format variant when meaningful (e.g. ASS vs SSA,
	 *  VobSub idx flavour).
	 */
	variant: string | null,
	/**
	 *  DVB teletext page number for teletext-based subtitle PIDs.  Always
	 *  `None` for non-DVB-TS files.
	 */
	teletextPage: number | null,
};

/**
 *  A single name/value tag pair sourced from container metadata
 *  (Matroska SimpleTag, MP4 iTunes ilst, ID3v2 frame, VorbisComment, ...).
 */
export type TagEntry = {
	name: string,
	value: string,
	/**  BCP-47 language code if the source format provides one. */
	language: string | null,
};

/**
 *  All container-level tags bucketed by reach.  Per-track tags live on each
 *  [`super::track::Track`] via `properties.tags`.
 */
export type TagsBundle = {
	/**
	 *  Tags that apply to the whole file (Matroska tags with no TrackUID, MP4
	 *  /moov/udta/meta, OGG VorbisComment block, ID3v2 frame outside MPEG
	 *  streams, ...).
	 */
	global: TagEntry[],
	/**
	 *  Sum of `Track.properties.tags.len()` across every track — duplicated
	 *  here so the frontend can rule out per-track tags without walking
	 *  `tracks[]`.  Always derived from the tracks list — never authored
	 *  independently.
	 */
	perTrackCount: number,
};

/**
 *  One track / stream / elementary substream of the parsed file.  The whole
 *  shape is camelCase with the domain sub-trees (`video / audio / subtitle`)
 *  stored as `Option<_>` so the frontend can ignore the irrelevant ones — see
 *  [[feedback-protocol-shape]].
 */
export type Track = {
	/**
	 *  0-based parser-assigned identifier — stable for a single parse
	 *  invocation, mirrors `mkvmerge -J` ordering.
	 */
	id: number,
	trackType: TrackType,
	codec: CodecInfo,
	properties: TrackProperties,
};

/**
 *  A presence-aware tri-state for `FlagEnabled` / `FlagDefault` / `FlagForced`.
 *  We distinguish "absent" from "explicitly false" so the frontend can fall
 *  back to the spec default rather than guess.
 */
export type TrackFlag = 
/**  Field not present in the source container; spec default applies. */
"unspecified" | "true" | "false";

/**
 *  Per-track properties.  `common` is always present; the domain sub-trees
 *  (`video / audio / subtitle`) are populated based on `track.trackType` and
 *  never share fields.
 */
export type TrackProperties = {
	common: CommonTrackProperties,
	video: VideoTrackProperties | null,
	audio: AudioTrackProperties | null,
	subtitle: SubtitleTrackProperties | null,
	tags: TagEntry[],
};

export type TrackType = "video" | "audio" | "subtitles" | "buttons" | "unknown";

/**
 *  Decoded codec-private blob for video tracks.  Fields are optional because
 *  not every codec populates every slot; the protocol shape is stable as we
 *  add codec-specific work in later phases.
 */
export type VideoCodecConfig = {
	profileName: string | null,
	profileIdc: number | null,
	levelName: string | null,
	levelIdc: number | null,
	tier: HevcTier | null,
	bitDepthLuma: number | null,
	bitDepthChroma: number | null,
	chromaFormat: ChromaFormat | null,
	codedDimensions: Dimensions2D | null,
	sampleAspectRatio: SampleAspectRatio | null,
	/**
	 *  Original codec-private bytes, hex-encoded.  Kept for transparency in
	 *  downstream tooling.
	 */
	rawHex: string | null,
	/**
	 *  `true` when the source provided a raw elementary stream (no container
	 *  wrap, e.g. `.h264` / `.265` / `.av1` file), `false` for in-container
	 *  payloads.  Mirrors mkvmerge's `mpeg4_p10_es_video` / `mpegh_p2_es_video`.
	 */
	isElementaryStream: boolean | null,
};

/**
 *  Video-track-only properties.  Populated only on tracks whose `trackType` is
 *  `Video`.  All sub-domains stay nested — see [[feedback-protocol-shape]].
 */
export type VideoTrackProperties = {
	/**  Encoded pixel dimensions (the raster). */
	pixelDimensions: Dimensions2D | null,
	/**  Intended display dimensions (PixelWidth/Height after PAR adjustment). */
	displayDimensions: Dimensions2D | null,
	/**  DisplayUnit — Matroska element 0x54B2.  Most files leave it implicit. */
	displayUnit: DisplayUnit | null,
	crop: CropRect | null,
	color: ColorMetadata | null,
	/**
	 *  Matroska `KaxVideoColourSpace` (0x2EB524) — raw FOURCC for uncompressed
	 *  tracks.  Hex-encoded so non-printable bytes round-trip safely.
	 */
	colorSpaceHex: string | null,
	projection: ProjectionMetadata | null,
	stereoMode: StereoMode | null,
	alphaMode: AlphaMode | null,
	fieldOrder: FieldOrder | null,
	interlace: InterlaceFlag | null,
	/**
	 *  Frame duration in nanoseconds.  When known we expose it as a typed u64;
	 *  frontend derives the implied frame rate.
	 */
	defaultDurationNs: number | null,
	codecConfig: VideoCodecConfig | null,
	/**
	 *  Display rotation, in degrees (0/90/180/270).  Derived from the MP4
	 *  tkhd display matrix when present; mirrors mkvtoolnix's
	 *  `mtx::qtmp4::compute_rotation_from_matrix`.  PARSER-069.
	 */
	rotationDegrees: number | null,
	/**
	 *  `true` when the source container signals a horizontal flip.  Derived
	 *  from a negative-determinant tkhd matrix.
	 */
	flipped: boolean | null,
	/**
	 *  Block-addition mappings — opaque per-frame side data the muxer carries
	 *  through verbatim.  PARSER-179: MP4 Dolby Vision configuration boxes
	 *  (`dvcC` / `dvvC` / `hvcE`) are stored here as
	 *  `block_addition_mapping_t{ id_type, id_extra_data }`
	 *  (`r_qtmp4.cpp:3318-3327`), not as the primary decoder configuration
	 *  record.
	 */
	blockAdditionMappings: BlockAdditionMapping[],
};

/**
 *  Non-fatal observations made during parse.  Fatal errors are returned as
 *  `Err(ParseError)` and never appear here.
 */
export type Warning = {
	category: WarningCategory,
	message: string,
	/**
	 *  Byte offset within the source file where the situation was detected,
	 *  or `None` for category-wide warnings that don't tie to a single byte.
	 */
	offset: number | null,
};

export type WarningCategory = 
/**
 *  Best-effort interpretation of a forward-compat field (e.g. EBML version
 *  newer than parser supports).
 */
"forwardCompat" | 
/**  Recognised but unsupported / un-decodable substructure was skipped. */
"skipped" | 
/**  Heuristic fallback was used because authoritative metadata was missing. */
"heuristic" | 
/**  Value was out of the spec-permitted range and was clamped. */
"clamped" | 
/**
 *  A registered language / codec id was not in the parser's lookup table;
 *  the raw value was passed through.
 */
"unknown";
